# Generated by Django 3.0.10 on 2022-08-06 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admisiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_adm', models.CharField(max_length=300)),
                ('requisitos', models.CharField(max_length=300)),
                ('fecha_expira', models.DateField()),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_carrera', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cel', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('archivo', models.BinaryField()),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Admisiones')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_registro', models.CharField(max_length=50)),
                ('estado_aprobacion', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('solicitd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='admisiones',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Carrera'),
        ),
    ]
