# Generated by Django 3.0.10 on 2022-08-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postulante',
            new_name='Postulantes',
        ),
    ]
