# Generated by Django 3.0.10 on 2022-08-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220806_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='admision',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='postulante',
        ),
        migrations.DeleteModel(
            name='Aprobacion',
        ),
        migrations.DeleteModel(
            name='Postulantes',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
