# Generated by Django 3.0.10 on 2022-08-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220806_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cel', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('archivo', models.BinaryField()),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
        ),
    ]
