# Generated by Django 3.0.10 on 2022-08-06 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_postulante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('admision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Admisiones')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_registro', models.CharField(max_length=50)),
                ('estado_aprobacion', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('solicitd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Solicitud')),
            ],
        ),
    ]
