# Generated by Django 3.0.10 on 2022-08-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aprobacion_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admisiones',
            name='descripcion_adm',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='admisiones',
            name='requisitos',
            field=models.CharField(max_length=500),
        ),
    ]
